{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ee2568e7-2057-4ba8-97e2-660e579cf246",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import pyodbc"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "aeaf3e1b-3303-435f-9800-457953fa32aa",
   "metadata": {},
   "outputs": [],
   "source": [
    "conn_str = (     r'driver={SQL Server};' \n",
    "            r'server=(local);'   \n",
    "            r'database=ODS;'   \n",
    "            r'trusted_connection=yes;'    ) \n",
    "cnxn = pyodbc.connect(conn_str) \n",
    "cursor = cnxn.cursor()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "b0748281-6915-4612-bec6-5210f363a736",
   "metadata": {},
   "outputs": [],
   "source": [
    "file=\"F:\\DWH\\DWH_IMPORT\\PIM Data\\PIM_Data.xlsx_2024-04-02_09-23-43.xlsx\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "25800484-dcb2-4900-a462-9a1056a41ace",
   "metadata": {},
   "outputs": [],
   "source": [
    "data=pd.read_excel(file)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "b35419c4-56e2-4322-b285-0585fe913185",
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.DataFrame(data)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "f30fad39-e189-4bec-b27f-5590615ca7e9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 74576 entries, 0 to 74575\n",
      "Data columns (total 46 columns):\n",
      " #   Column                        Non-Null Count  Dtype  \n",
      "---  ------                        --------------  -----  \n",
      " 0   sys_id                        74576 non-null  int64  \n",
      " 1   sys_entitytype                74576 non-null  object \n",
      " 2   ProductLevel0                 74576 non-null  object \n",
      " 3   ProductLevel0_en              74576 non-null  object \n",
      " 4   ProductLevel1                 74576 non-null  object \n",
      " 5   ProductLevel1_en              74576 non-null  object \n",
      " 6   ProductLevel2                 74576 non-null  object \n",
      " 7   ProductLevel2_en              74576 non-null  object \n",
      " 8   ProductLevel3                 74576 non-null  object \n",
      " 9   ProductLevel3_en              74576 non-null  object \n",
      " 10  ProductLevel4                 74576 non-null  object \n",
      " 11  ProductLevel4_en              74576 non-null  object \n",
      " 12  ProductFamily1                74496 non-null  float64\n",
      " 13  ProductFamily1 (values)       74496 non-null  object \n",
      " 14  ItemNumber                    62585 non-null  object \n",
      " 15  ItemLifeCycleStatus           62585 non-null  float64\n",
      " 16  ItemLifeCycleStatus (values)  62585 non-null  object \n",
      " 17  ItemPNSupplier                62345 non-null  object \n",
      " 18  ItemPNHUB                     37130 non-null  object \n",
      " 19  ItemPNARG                     2343 non-null   object \n",
      " 20  ItemPNAUS                     11416 non-null  object \n",
      " 21  ItemPNCOL                     2078 non-null   object \n",
      " 22  ItemPNCZ                      6142 non-null   object \n",
      " 23  ItemPNFIN                     10267 non-null  object \n",
      " 24  ItemPNFR                      13295 non-null  object \n",
      " 25  ItemPNLIT                     4514 non-null   object \n",
      " 26  ItemPNNL                      25206 non-null  object \n",
      " 27  ItemPNOEMCZ                   6881 non-null   object \n",
      " 28  ItemPNOEMFRA                  183 non-null    object \n",
      " 29  ItemPNOEMKOR                  251 non-null    object \n",
      " 30  ItemPNOEMPSI                  1260 non-null   object \n",
      " 31  ItemPNOEMRHAM                 982 non-null    object \n",
      " 32  ItemPNOEMUK                   6759 non-null   object \n",
      " 33  ItemPNPER                     4576 non-null   object \n",
      " 34  ItemPNPOL                     12509 non-null  object \n",
      " 35  ItemPNSA                      5558 non-null   object \n",
      " 36  ItemPNSGN                     5361 non-null   object \n",
      " 37  ItemPNUAE                     3726 non-null   object \n",
      " 38  ItemPNUK                      2187 non-null   object \n",
      " 39  ItemPNHYSP                    4835 non-null   object \n",
      " 40  ItemPNSEAFR                   4644 non-null   object \n",
      " 41  ItemPNRHAU                    1539 non-null   object \n",
      " 42  ItemPNRHNZ                    6464 non-null   object \n",
      " 43  ItemPNRHZA                    523 non-null    object \n",
      " 44  ItemSupplier                  62558 non-null  object \n",
      " 45  ItemSupplier (values)         62558 non-null  object \n",
      "dtypes: float64(2), int64(1), object(43)\n",
      "memory usage: 26.2+ MB\n"
     ]
    }
   ],
   "source": [
    "df.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "dd64472f-8567-4727-98c8-ffba9f2d144c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>sys_id</th>\n",
       "      <th>sys_entitytype</th>\n",
       "      <th>ProductLevel0</th>\n",
       "      <th>ProductLevel0_en</th>\n",
       "      <th>ProductLevel1</th>\n",
       "      <th>ProductLevel1_en</th>\n",
       "      <th>ProductLevel2</th>\n",
       "      <th>ProductLevel2_en</th>\n",
       "      <th>ProductLevel3</th>\n",
       "      <th>ProductLevel3_en</th>\n",
       "      <th>...</th>\n",
       "      <th>ItemPNSGN</th>\n",
       "      <th>ItemPNUAE</th>\n",
       "      <th>ItemPNUK</th>\n",
       "      <th>ItemPNHYSP</th>\n",
       "      <th>ItemPNSEAFR</th>\n",
       "      <th>ItemPNRHAU</th>\n",
       "      <th>ItemPNRHNZ</th>\n",
       "      <th>ItemPNRHZA</th>\n",
       "      <th>ItemSupplier</th>\n",
       "      <th>ItemSupplier (values)</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>22043</td>\n",
       "      <td>Product</td>\n",
       "      <td>Hoses</td>\n",
       "      <td>Hoses</td>\n",
       "      <td>HydraulicHoses</td>\n",
       "      <td>Hydraulic Hoses</td>\n",
       "      <td>HydraulicHosesWireBraid</td>\n",
       "      <td>Hydraulic Hoses Wire Braid</td>\n",
       "      <td>HydraulicHosesWireBraidStandard</td>\n",
       "      <td>Hydraulic Hoses Wire Braid Standard</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>23708</td>\n",
       "      <td>Item</td>\n",
       "      <td>Hoses</td>\n",
       "      <td>Hoses</td>\n",
       "      <td>HydraulicHoses</td>\n",
       "      <td>Hydraulic Hoses</td>\n",
       "      <td>HydraulicHosesWireBraid</td>\n",
       "      <td>Hydraulic Hoses Wire Braid</td>\n",
       "      <td>HydraulicHosesWireBraidStandard</td>\n",
       "      <td>Hydraulic Hoses Wire Braid Standard</td>\n",
       "      <td>...</td>\n",
       "      <td>H01006016</td>\n",
       "      <td>0000001453</td>\n",
       "      <td>421SN-10</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>S0001</td>\n",
       "      <td>Manuli Hydraulics Polska Legnica</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>2 rows × 46 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "   sys_id sys_entitytype ProductLevel0 ProductLevel0_en   ProductLevel1  \\\n",
       "0   22043        Product         Hoses            Hoses  HydraulicHoses   \n",
       "1   23708           Item         Hoses            Hoses  HydraulicHoses   \n",
       "\n",
       "  ProductLevel1_en            ProductLevel2            ProductLevel2_en  \\\n",
       "0  Hydraulic Hoses  HydraulicHosesWireBraid  Hydraulic Hoses Wire Braid   \n",
       "1  Hydraulic Hoses  HydraulicHosesWireBraid  Hydraulic Hoses Wire Braid   \n",
       "\n",
       "                     ProductLevel3                     ProductLevel3_en  ...  \\\n",
       "0  HydraulicHosesWireBraidStandard  Hydraulic Hoses Wire Braid Standard  ...   \n",
       "1  HydraulicHosesWireBraidStandard  Hydraulic Hoses Wire Braid Standard  ...   \n",
       "\n",
       "   ItemPNSGN   ItemPNUAE  ItemPNUK ItemPNHYSP ItemPNSEAFR  ItemPNRHAU  \\\n",
       "0        NaN         NaN       NaN        NaN         NaN         NaN   \n",
       "1  H01006016  0000001453  421SN-10        NaN         NaN         NaN   \n",
       "\n",
       "  ItemPNRHNZ ItemPNRHZA ItemSupplier             ItemSupplier (values)  \n",
       "0        NaN        NaN          NaN                               NaN  \n",
       "1        NaN        NaN        S0001  Manuli Hydraulics Polska Legnica  \n",
       "\n",
       "[2 rows x 46 columns]"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.head(2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "fd1d44e2-0ba0-4b32-b41c-90e6d6627ade",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0                     NaN\n",
       "1           A01001-10B001\n",
       "2           A01001-12B001\n",
       "3           A01001-16B001\n",
       "4           A01001-20B001\n",
       "               ...       \n",
       "74571    B17043-12-10A009\n",
       "74572    B17043-12-12A009\n",
       "74573    B17043-12-14A009\n",
       "74574    B17043-16-12A009\n",
       "74575    B17043-16-16A009\n",
       "Name: ItemNumber, Length: 74576, dtype: object"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df['ItemNumber']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "c7519c6d-ad1a-4277-b54c-4f5a64291ffb",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\admin.nasim\\AppData\\Local\\Temp\\3\\ipykernel_17000\\1162803613.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value ' ' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.\n",
      "  df.fillna(\" \", inplace=True)\n"
     ]
    }
   ],
   "source": [
    "#df.fillna(0, inplace=True)\n",
    "df.fillna(\" \", inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "d1cff8ac-b84d-44e2-9368-a11c70cf6745",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 74576 entries, 0 to 74575\n",
      "Data columns (total 46 columns):\n",
      " #   Column                        Non-Null Count  Dtype \n",
      "---  ------                        --------------  ----- \n",
      " 0   sys_id                        74576 non-null  int64 \n",
      " 1   sys_entitytype                74576 non-null  object\n",
      " 2   ProductLevel0                 74576 non-null  object\n",
      " 3   ProductLevel0_en              74576 non-null  object\n",
      " 4   ProductLevel1                 74576 non-null  object\n",
      " 5   ProductLevel1_en              74576 non-null  object\n",
      " 6   ProductLevel2                 74576 non-null  object\n",
      " 7   ProductLevel2_en              74576 non-null  object\n",
      " 8   ProductLevel3                 74576 non-null  object\n",
      " 9   ProductLevel3_en              74576 non-null  object\n",
      " 10  ProductLevel4                 74576 non-null  object\n",
      " 11  ProductLevel4_en              74576 non-null  object\n",
      " 12  ProductFamily1                74576 non-null  object\n",
      " 13  ProductFamily1 (values)       74576 non-null  object\n",
      " 14  ItemNumber                    74576 non-null  object\n",
      " 15  ItemLifeCycleStatus           74576 non-null  object\n",
      " 16  ItemLifeCycleStatus (values)  74576 non-null  object\n",
      " 17  ItemPNSupplier                74576 non-null  object\n",
      " 18  ItemPNHUB                     74576 non-null  object\n",
      " 19  ItemPNARG                     74576 non-null  object\n",
      " 20  ItemPNAUS                     74576 non-null  object\n",
      " 21  ItemPNCOL                     74576 non-null  object\n",
      " 22  ItemPNCZ                      74576 non-null  object\n",
      " 23  ItemPNFIN                     74576 non-null  object\n",
      " 24  ItemPNFR                      74576 non-null  object\n",
      " 25  ItemPNLIT                     74576 non-null  object\n",
      " 26  ItemPNNL                      74576 non-null  object\n",
      " 27  ItemPNOEMCZ                   74576 non-null  object\n",
      " 28  ItemPNOEMFRA                  74576 non-null  object\n",
      " 29  ItemPNOEMKOR                  74576 non-null  object\n",
      " 30  ItemPNOEMPSI                  74576 non-null  object\n",
      " 31  ItemPNOEMRHAM                 74576 non-null  object\n",
      " 32  ItemPNOEMUK                   74576 non-null  object\n",
      " 33  ItemPNPER                     74576 non-null  object\n",
      " 34  ItemPNPOL                     74576 non-null  object\n",
      " 35  ItemPNSA                      74576 non-null  object\n",
      " 36  ItemPNSGN                     74576 non-null  object\n",
      " 37  ItemPNUAE                     74576 non-null  object\n",
      " 38  ItemPNUK                      74576 non-null  object\n",
      " 39  ItemPNHYSP                    74576 non-null  object\n",
      " 40  ItemPNSEAFR                   74576 non-null  object\n",
      " 41  ItemPNRHAU                    74576 non-null  object\n",
      " 42  ItemPNRHNZ                    74576 non-null  object\n",
      " 43  ItemPNRHZA                    74576 non-null  object\n",
      " 44  ItemSupplier                  74576 non-null  object\n",
      " 45  ItemSupplier (values)         74576 non-null  object\n",
      "dtypes: int64(1), object(45)\n",
      "memory usage: 26.2+ MB\n"
     ]
    }
   ],
   "source": [
    "df.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "4474d8c5-f309-4f80-92f9-aafc2b582506",
   "metadata": {},
   "outputs": [],
   "source": [
    "cursor.execute('''\n",
    "               CREATE TABLE products\n",
    "                    (sys_id INT NOT NULL,\n",
    "                    sys_entitytype  VARCHAR(100) NOT NULL,\n",
    "                    ProductLevel0 VARCHAR(100) NOT NULL,\n",
    "                    ProductLevel0_en VARCHAR(100) NOT NULL,\n",
    "                    ProductLevel1  VARCHAR(100) NOT NULL,\n",
    "                    ProductLevel1_en  VARCHAR(100) NOT NULL,\n",
    "                    ProductLevel2 VARCHAR(100) NOT NULL,\n",
    "                    ProductLevel2_en VARCHAR(100) NOT NULL,\n",
    "                    ProductLevel3  VARCHAR(100) NOT NULL,\n",
    "                    ProductLevel3_en  VARCHAR(100) NOT NULL,\n",
    "                    ProductLevel4 VARCHAR(100) NOT NULL,\n",
    "                    ProductLevel4_en VARCHAR(100) NOT NULL,\n",
    "                    ProductFamily1  FLOAT NOT NULL,\n",
    "                    [ProductFamily1 (values)] VARCHAR(100) NOT NULL,\n",
    "                    ItemNumber VARCHAR(100) NOT NULL,\n",
    "                    ItemLifeCycleStatus FLOAT NOT NULL,\n",
    "                    [ItemLifeCycleStatus (values)] VARCHAR(100) NOT NULL,\n",
    "                    ItemPNSupplier VARCHAR(100) NOT NULL,\n",
    "                    ItemPNHUB VARCHAR(100) NOT NULL,\n",
    "                    ItemPNARG  VARCHAR(100) NOT NULL,\n",
    "                    ItemPNAUS  VARCHAR(100) NOT NULL,\n",
    "                    ItemPNCOL VARCHAR(100) NOT NULL,\n",
    "                    ItemPNCZ VARCHAR(100) NOT NULL,\n",
    "                    ItemPNFIN  VARCHAR(100) NOT NULL,\n",
    "                    ItemPNFR  VARCHAR(100) NOT NULL,\n",
    "                    ItemPNLIT VARCHAR(100) NOT NULL,\n",
    "                    ItemPNNL VARCHAR(100) NOT NULL,\n",
    "                    ItemPNOEMCZ  VARCHAR(100) NOT NULL,\n",
    "                    ItemPNOEMFRA  VARCHAR(100) NOT NULL,\n",
    "                    ItemPNOEMKOR VARCHAR(100) NOT NULL,\n",
    "                    ItemPNOEMPSI VARCHAR(100) NOT NULL,\n",
    "                    ItemPNOEMRHAM  VARCHAR(100) NOT NULL,\n",
    "                    ItemPNOEMUK  VARCHAR(100) NOT NULL,\n",
    "                    ItemPNPER VARCHAR(100) NOT NULL,\n",
    "                    ItemPNPOL VARCHAR(100) NOT NULL,\n",
    "                    ItemPNSGN  VARCHAR(100) NOT NULL,\n",
    "                    ItemPNUAE  VARCHAR(100) NOT NULL,\n",
    "                    ItemPNUK VARCHAR(100) NOT NULL,\n",
    "                    ItemPNHYSP VARCHAR(100) NOT NULL,\n",
    "                    ItemPNSEAFR  VARCHAR(100) NOT NULL,\n",
    "                    ItemPNRHAU  VARCHAR(100) NOT NULL,\n",
    "                    ItemPNRHNZ VARCHAR(100) NOT NULL,\n",
    "                    ItemPNRHZA VARCHAR(100) NOT NULL,\n",
    "                    ItemSupplier  VARCHAR(100) NOT NULL,\n",
    "                    [ItemSupplier (values)] VARCHAR(100) NOT NULL,)\n",
    "                   \n",
    "               ;\n",
    "               ''')\n",
    "cnxn.commit()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "98858d1f-cf99-48ff-a863-58df40217c71",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\admin.nasim\\AppData\\Local\\Temp\\3\\ipykernel_17000\\2815385543.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_NewDF = pd.read_sql(query, cnxn)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>sys_id</th>\n",
       "      <th>sys_entitytype</th>\n",
       "      <th>ProductLevel0</th>\n",
       "      <th>ProductLevel0_en</th>\n",
       "      <th>ProductLevel1</th>\n",
       "      <th>ProductLevel1_en</th>\n",
       "      <th>ProductLevel2</th>\n",
       "      <th>ProductLevel2_en</th>\n",
       "      <th>ProductLevel3</th>\n",
       "      <th>ProductLevel3_en</th>\n",
       "      <th>...</th>\n",
       "      <th>ItemPNSGN</th>\n",
       "      <th>ItemPNUAE</th>\n",
       "      <th>ItemPNUK</th>\n",
       "      <th>ItemPNHYSP</th>\n",
       "      <th>ItemPNSEAFR</th>\n",
       "      <th>ItemPNRHAU</th>\n",
       "      <th>ItemPNRHNZ</th>\n",
       "      <th>ItemPNRHZA</th>\n",
       "      <th>ItemSupplier</th>\n",
       "      <th>ItemSupplier (values)</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>0 rows × 45 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "Empty DataFrame\n",
       "Columns: [sys_id, sys_entitytype, ProductLevel0, ProductLevel0_en, ProductLevel1, ProductLevel1_en, ProductLevel2, ProductLevel2_en, ProductLevel3, ProductLevel3_en, ProductLevel4, ProductLevel4_en, ProductFamily1, ProductFamily1 (values), ItemNumber, ItemLifeCycleStatus, ItemLifeCycleStatus (values), ItemPNSupplier, ItemPNHUB, ItemPNARG, ItemPNAUS, ItemPNCOL, ItemPNCZ, ItemPNFIN, ItemPNFR, ItemPNLIT, ItemPNNL, ItemPNOEMCZ, ItemPNOEMFRA, ItemPNOEMKOR, ItemPNOEMPSI, ItemPNOEMRHAM, ItemPNOEMUK, ItemPNPER, ItemPNPOL, ItemPNSGN, ItemPNUAE, ItemPNUK, ItemPNHYSP, ItemPNSEAFR, ItemPNRHAU, ItemPNRHNZ, ItemPNRHZA, ItemSupplier, ItemSupplier (values)]\n",
       "Index: []\n",
       "\n",
       "[0 rows x 45 columns]"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "query = '''\n",
    "        SELECT * \n",
    "            FROM products\n",
    "        ;\n",
    "            '''\n",
    "\n",
    "df_NewDF = pd.read_sql(query, cnxn)\n",
    "df_NewDF.head(2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "6478f198-ce00-411c-9fff-025ed40f9d90",
   "metadata": {},
   "outputs": [],
   "source": [
    "for index, row in df.iterrows():\n",
    "     cursor.execute('''\n",
    "                    INSERT INTO dbo.products \n",
    "                    (sys_id,\n",
    "                    sys_entitytype,\n",
    "                    ProductLevel0,\n",
    "                    ProductLevel0_en,\n",
    "                    ProductLevel1,\n",
    "                    ProductLevel1_en,\n",
    "                    ProductLevel2,\n",
    "                    ProductLevel2_en,\n",
    "                    ProductLevel3,\n",
    "                    ProductLevel3_en,\n",
    "                    ProductLevel4,\n",
    "                    ProductLevel4_en,\n",
    "                    ProductFamily1,\n",
    "                    [ProductFamily1 (values)],\n",
    "                    ItemNumber,\n",
    "                    ItemLifeCycleStatus,\n",
    "                    [ItemLifeCycleStatus (values)],\n",
    "                    ItemPNSupplier,\n",
    "                    ItemPNHUB,\n",
    "                    ItemPNARG,\n",
    "                    ItemPNAUS,\n",
    "                    ItemPNCOL,\n",
    "                    ItemPNCZ,\n",
    "                    ItemPNFIN,\n",
    "                    ItemPNFR,\n",
    "                    ItemPNLIT,\n",
    "                    ItemPNNL,\n",
    "                    ItemPNOEMCZ,\n",
    "                    ItemPNOEMFRA,\n",
    "                    ItemPNOEMKOR,\n",
    "                    ItemPNOEMPSI,\n",
    "                    ItemPNOEMRHAM,\n",
    "                    ItemPNOEMUK,\n",
    "                    ItemPNPER,\n",
    "                    ItemPNPOL,\n",
    "                    ItemPNSGN,\n",
    "                    ItemPNUAE,\n",
    "                    ItemPNUK,\n",
    "                    ItemPNHYSP,\n",
    "                    ItemPNSEAFR,\n",
    "                    ItemPNRHAU,\n",
    "                    ItemPNRHNZ,\n",
    "                    ItemPNRHZA,\n",
    "                    ItemSupplier,\n",
    "                    [ItemSupplier (values)]) \n",
    "                    values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)\n",
    "                    ''', \n",
    "                    row.sys_id, \n",
    "                    row.sys_entitytype, \n",
    "                    row.ProductLevel0, \n",
    "                    row.ProductLevel0_en,\n",
    "                    row.ProductLevel1,\n",
    "                    row.ProductLevel1_en,\n",
    "                    row.ProductLevel2,\n",
    "                    row.ProductLevel2_en,\n",
    "                    row.ProductLevel3,\n",
    "                    row.ProductLevel3_en,\n",
    "                    row.ProductLevel4,\n",
    "                    row.ProductLevel4_en,\n",
    "                    row.ProductFamily1,\n",
    "                    row['ProductFamily1 (values)'],\n",
    "                    row.ItemNumber,\n",
    "                    row.ItemLifeCycleStatus,\n",
    "                    row['ItemLifeCycleStatus (values)'],\n",
    "                    row.ItemPNSupplier,\n",
    "                    row.ItemPNHUB,\n",
    "                    row.ItemPNARG,\n",
    "                    row.ItemPNAUS,\n",
    "                    row.ItemPNCOL,\n",
    "                    row.ItemPNCZ,\n",
    "                    row.ItemPNFIN,\n",
    "                    row.ItemPNFR,\n",
    "                    row.ItemPNLIT,\n",
    "                    row.ItemPNNL,\n",
    "                    row.ItemPNOEMCZ,\n",
    "                    row.ItemPNOEMFRA,\n",
    "                    row.ItemPNOEMKOR,\n",
    "                    row.ItemPNOEMPSI,\n",
    "                    row.ItemPNOEMRHAM,\n",
    "                    row.ItemPNOEMUK,\n",
    "                    row.ItemPNPER,\n",
    "                    row.ItemPNPOL,\n",
    "                    row.ItemPNSGN,\n",
    "                    row.ItemPNUAE,\n",
    "                    row.ItemPNUK,\n",
    "                    row.ItemPNHYSP,\n",
    "                    row.ItemPNSEAFR,\n",
    "                    row.ItemPNRHAU,\n",
    "                    row.ItemPNRHNZ,\n",
    "                    row.ItemPNRHZA,\n",
    "                    row.ItemSupplier,\n",
    "                    row['ItemSupplier (values)'])\n",
    "cnxn.commit()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "63793967-0379-4f13-af15-4347fef85748",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\admin.nasim\\AppData\\Local\\Temp\\3\\ipykernel_17000\\2691658093.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_NewDF1 = pd.read_sql(query, cnxn)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>sys_id</th>\n",
       "      <th>sys_entitytype</th>\n",
       "      <th>ProductLevel0</th>\n",
       "      <th>ProductLevel0_en</th>\n",
       "      <th>ProductLevel1</th>\n",
       "      <th>ProductLevel1_en</th>\n",
       "      <th>ProductLevel2</th>\n",
       "      <th>ProductLevel2_en</th>\n",
       "      <th>ProductLevel3</th>\n",
       "      <th>ProductLevel3_en</th>\n",
       "      <th>...</th>\n",
       "      <th>ItemPNSGN</th>\n",
       "      <th>ItemPNUAE</th>\n",
       "      <th>ItemPNUK</th>\n",
       "      <th>ItemPNHYSP</th>\n",
       "      <th>ItemPNSEAFR</th>\n",
       "      <th>ItemPNRHAU</th>\n",
       "      <th>ItemPNRHNZ</th>\n",
       "      <th>ItemPNRHZA</th>\n",
       "      <th>ItemSupplier</th>\n",
       "      <th>ItemSupplier (values)</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>22043</td>\n",
       "      <td>Product</td>\n",
       "      <td>Hoses</td>\n",
       "      <td>Hoses</td>\n",
       "      <td>HydraulicHoses</td>\n",
       "      <td>Hydraulic Hoses</td>\n",
       "      <td>HydraulicHosesWireBraid</td>\n",
       "      <td>Hydraulic Hoses Wire Braid</td>\n",
       "      <td>HydraulicHosesWireBraidStandard</td>\n",
       "      <td>Hydraulic Hoses Wire Braid Standard</td>\n",
       "      <td>...</td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>23708</td>\n",
       "      <td>Item</td>\n",
       "      <td>Hoses</td>\n",
       "      <td>Hoses</td>\n",
       "      <td>HydraulicHoses</td>\n",
       "      <td>Hydraulic Hoses</td>\n",
       "      <td>HydraulicHosesWireBraid</td>\n",
       "      <td>Hydraulic Hoses Wire Braid</td>\n",
       "      <td>HydraulicHosesWireBraidStandard</td>\n",
       "      <td>Hydraulic Hoses Wire Braid Standard</td>\n",
       "      <td>...</td>\n",
       "      <td>H01006016</td>\n",
       "      <td>0000001453</td>\n",
       "      <td>421SN-10</td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td>S0001</td>\n",
       "      <td>Manuli Hydraulics Polska Legnica</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>2 rows × 45 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "   sys_id sys_entitytype ProductLevel0 ProductLevel0_en   ProductLevel1  \\\n",
       "0   22043        Product         Hoses            Hoses  HydraulicHoses   \n",
       "1   23708           Item         Hoses            Hoses  HydraulicHoses   \n",
       "\n",
       "  ProductLevel1_en            ProductLevel2            ProductLevel2_en  \\\n",
       "0  Hydraulic Hoses  HydraulicHosesWireBraid  Hydraulic Hoses Wire Braid   \n",
       "1  Hydraulic Hoses  HydraulicHosesWireBraid  Hydraulic Hoses Wire Braid   \n",
       "\n",
       "                     ProductLevel3                     ProductLevel3_en  ...  \\\n",
       "0  HydraulicHosesWireBraidStandard  Hydraulic Hoses Wire Braid Standard  ...   \n",
       "1  HydraulicHosesWireBraidStandard  Hydraulic Hoses Wire Braid Standard  ...   \n",
       "\n",
       "   ItemPNSGN   ItemPNUAE  ItemPNUK ItemPNHYSP ItemPNSEAFR  ItemPNRHAU  \\\n",
       "0                                                                       \n",
       "1  H01006016  0000001453  421SN-10                                      \n",
       "\n",
       "  ItemPNRHNZ ItemPNRHZA ItemSupplier             ItemSupplier (values)  \n",
       "0                                                                       \n",
       "1                              S0001  Manuli Hydraulics Polska Legnica  \n",
       "\n",
       "[2 rows x 45 columns]"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "query = '''\n",
    "        SELECT * \n",
    "            FROM products\n",
    "        ;\n",
    "            '''\n",
    "\n",
    "df_NewDF1 = pd.read_sql(query, cnxn)\n",
    "df_NewDF1.head(2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "4c0caa47-4330-49b2-b467-c0928c3def29",
   "metadata": {},
   "outputs": [],
   "source": [
    "cursor.execute( '''\n",
    "        truncate table products\n",
    "        \n",
    "               ;\n",
    "               ''')\n",
    "cnxn.commit()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "1485d893-07cc-4233-8ef5-1939760f9e48",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\admin.nasim\\AppData\\Local\\Temp\\3\\ipykernel_17000\\529068381.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_NewDF2 = pd.read_sql(query, cnxn)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>sys_id</th>\n",
       "      <th>sys_entitytype</th>\n",
       "      <th>ProductLevel0</th>\n",
       "      <th>ProductLevel0_en</th>\n",
       "      <th>ProductLevel1</th>\n",
       "      <th>ProductLevel1_en</th>\n",
       "      <th>ProductLevel2</th>\n",
       "      <th>ProductLevel2_en</th>\n",
       "      <th>ProductLevel3</th>\n",
       "      <th>ProductLevel3_en</th>\n",
       "      <th>...</th>\n",
       "      <th>ItemPNSGN</th>\n",
       "      <th>ItemPNUAE</th>\n",
       "      <th>ItemPNUK</th>\n",
       "      <th>ItemPNHYSP</th>\n",
       "      <th>ItemPNSEAFR</th>\n",
       "      <th>ItemPNRHAU</th>\n",
       "      <th>ItemPNRHNZ</th>\n",
       "      <th>ItemPNRHZA</th>\n",
       "      <th>ItemSupplier</th>\n",
       "      <th>ItemSupplier (values)</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>0 rows × 45 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "Empty DataFrame\n",
       "Columns: [sys_id, sys_entitytype, ProductLevel0, ProductLevel0_en, ProductLevel1, ProductLevel1_en, ProductLevel2, ProductLevel2_en, ProductLevel3, ProductLevel3_en, ProductLevel4, ProductLevel4_en, ProductFamily1, ProductFamily1 (values), ItemNumber, ItemLifeCycleStatus, ItemLifeCycleStatus (values), ItemPNSupplier, ItemPNHUB, ItemPNARG, ItemPNAUS, ItemPNCOL, ItemPNCZ, ItemPNFIN, ItemPNFR, ItemPNLIT, ItemPNNL, ItemPNOEMCZ, ItemPNOEMFRA, ItemPNOEMKOR, ItemPNOEMPSI, ItemPNOEMRHAM, ItemPNOEMUK, ItemPNPER, ItemPNPOL, ItemPNSGN, ItemPNUAE, ItemPNUK, ItemPNHYSP, ItemPNSEAFR, ItemPNRHAU, ItemPNRHNZ, ItemPNRHZA, ItemSupplier, ItemSupplier (values)]\n",
       "Index: []\n",
       "\n",
       "[0 rows x 45 columns]"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "query = '''\n",
    "        SELECT * \n",
    "            FROM products\n",
    "        ;\n",
    "            '''\n",
    "\n",
    "df_NewDF2 = pd.read_sql(query, cnxn)\n",
    "df_NewDF2.head(2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "aa09c773-3d63-4581-9701-eed05a3cdfe5",
   "metadata": {},
   "outputs": [],
   "source": [
    "cursor.execute( '''\n",
    "        Drop table products\n",
    "        \n",
    "               ;\n",
    "               ''')\n",
    "cnxn.commit()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "fcb0b23d-c7a2-40c8-aee2-aefaa0e11da8",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\admin.nasim\\AppData\\Local\\Temp\\3\\ipykernel_17000\\2691658093.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_NewDF1 = pd.read_sql(query, cnxn)\n"
     ]
    },
    {
     "ename": "DatabaseError",
     "evalue": "Execution failed on sql '\n        SELECT * \n            FROM products\n        ;\n            ': ('42S02', \"[42S02] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name 'products'. (208) (SQLExecDirectW)\")",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mProgrammingError\u001b[0m                          Traceback (most recent call last)",
      "File \u001b[1;32m~\\AppData\\Local\\anaconda3\\Lib\\site-packages\\pandas\\io\\sql.py:2262\u001b[0m, in \u001b[0;36mSQLiteDatabase.execute\u001b[1;34m(self, sql, params)\u001b[0m\n\u001b[0;32m   2261\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m-> 2262\u001b[0m     cur\u001b[38;5;241m.\u001b[39mexecute(sql, \u001b[38;5;241m*\u001b[39margs)\n\u001b[0;32m   2263\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m cur\n",
      "\u001b[1;31mProgrammingError\u001b[0m: ('42S02', \"[42S02] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name 'products'. (208) (SQLExecDirectW)\")",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[1;31mDatabaseError\u001b[0m                             Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[18], line 7\u001b[0m\n\u001b[0;32m      1\u001b[0m query \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m'''\u001b[39m\n\u001b[0;32m      2\u001b[0m \u001b[38;5;124m        SELECT * \u001b[39m\n\u001b[0;32m      3\u001b[0m \u001b[38;5;124m            FROM products\u001b[39m\n\u001b[0;32m      4\u001b[0m \u001b[38;5;124m        ;\u001b[39m\n\u001b[0;32m      5\u001b[0m \u001b[38;5;124m            \u001b[39m\u001b[38;5;124m'''\u001b[39m\n\u001b[1;32m----> 7\u001b[0m df_NewDF1 \u001b[38;5;241m=\u001b[39m pd\u001b[38;5;241m.\u001b[39mread_sql(query, cnxn)\n\u001b[0;32m      8\u001b[0m df_NewDF1\u001b[38;5;241m.\u001b[39mhead(\u001b[38;5;241m2\u001b[39m)\n",
      "File \u001b[1;32m~\\AppData\\Local\\anaconda3\\Lib\\site-packages\\pandas\\io\\sql.py:654\u001b[0m, in \u001b[0;36mread_sql\u001b[1;34m(sql, con, index_col, coerce_float, params, parse_dates, columns, chunksize, dtype_backend, dtype)\u001b[0m\n\u001b[0;32m    652\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m pandasSQL_builder(con) \u001b[38;5;28;01mas\u001b[39;00m pandas_sql:\n\u001b[0;32m    653\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(pandas_sql, SQLiteDatabase):\n\u001b[1;32m--> 654\u001b[0m         \u001b[38;5;28;01mreturn\u001b[39;00m pandas_sql\u001b[38;5;241m.\u001b[39mread_query(\n\u001b[0;32m    655\u001b[0m             sql,\n\u001b[0;32m    656\u001b[0m             index_col\u001b[38;5;241m=\u001b[39mindex_col,\n\u001b[0;32m    657\u001b[0m             params\u001b[38;5;241m=\u001b[39mparams,\n\u001b[0;32m    658\u001b[0m             coerce_float\u001b[38;5;241m=\u001b[39mcoerce_float,\n\u001b[0;32m    659\u001b[0m             parse_dates\u001b[38;5;241m=\u001b[39mparse_dates,\n\u001b[0;32m    660\u001b[0m             chunksize\u001b[38;5;241m=\u001b[39mchunksize,\n\u001b[0;32m    661\u001b[0m             dtype_backend\u001b[38;5;241m=\u001b[39mdtype_backend,\n\u001b[0;32m    662\u001b[0m             dtype\u001b[38;5;241m=\u001b[39mdtype,\n\u001b[0;32m    663\u001b[0m         )\n\u001b[0;32m    665\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m    666\u001b[0m         _is_table_name \u001b[38;5;241m=\u001b[39m pandas_sql\u001b[38;5;241m.\u001b[39mhas_table(sql)\n",
      "File \u001b[1;32m~\\AppData\\Local\\anaconda3\\Lib\\site-packages\\pandas\\io\\sql.py:2326\u001b[0m, in \u001b[0;36mSQLiteDatabase.read_query\u001b[1;34m(self, sql, index_col, coerce_float, parse_dates, params, chunksize, dtype, dtype_backend)\u001b[0m\n\u001b[0;32m   2315\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mread_query\u001b[39m(\n\u001b[0;32m   2316\u001b[0m     \u001b[38;5;28mself\u001b[39m,\n\u001b[0;32m   2317\u001b[0m     sql,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   2324\u001b[0m     dtype_backend: DtypeBackend \u001b[38;5;241m|\u001b[39m Literal[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mnumpy\u001b[39m\u001b[38;5;124m\"\u001b[39m] \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mnumpy\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[0;32m   2325\u001b[0m ) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m DataFrame \u001b[38;5;241m|\u001b[39m Iterator[DataFrame]:\n\u001b[1;32m-> 2326\u001b[0m     cursor \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mexecute(sql, params)\n\u001b[0;32m   2327\u001b[0m     columns \u001b[38;5;241m=\u001b[39m [col_desc[\u001b[38;5;241m0\u001b[39m] \u001b[38;5;28;01mfor\u001b[39;00m col_desc \u001b[38;5;129;01min\u001b[39;00m cursor\u001b[38;5;241m.\u001b[39mdescription]\n\u001b[0;32m   2329\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m chunksize \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "File \u001b[1;32m~\\AppData\\Local\\anaconda3\\Lib\\site-packages\\pandas\\io\\sql.py:2274\u001b[0m, in \u001b[0;36mSQLiteDatabase.execute\u001b[1;34m(self, sql, params)\u001b[0m\n\u001b[0;32m   2271\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m ex \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01minner_exc\u001b[39;00m\n\u001b[0;32m   2273\u001b[0m ex \u001b[38;5;241m=\u001b[39m DatabaseError(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mExecution failed on sql \u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;132;01m{\u001b[39;00msql\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mexc\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m-> 2274\u001b[0m \u001b[38;5;28;01mraise\u001b[39;00m ex \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mexc\u001b[39;00m\n",
      "\u001b[1;31mDatabaseError\u001b[0m: Execution failed on sql '\n        SELECT * \n            FROM products\n        ;\n            ': ('42S02', \"[42S02] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name 'products'. (208) (SQLExecDirectW)\")"
     ]
    }
   ],
   "source": [
    "query = '''\n",
    "        SELECT * \n",
    "            FROM products\n",
    "        ;\n",
    "            '''\n",
    "\n",
    "df_NewDF1 = pd.read_sql(query, cnxn)\n",
    "df_NewDF1.head(2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b9074f85-4524-457d-bdef-c963c288552d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
